name: Build and Deploy Java Code to AWS EC2

on:
  workflow_dispatch:


jobs:
  build-and-deploy-java-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install JDK and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build Java code
        run: mvn -B clean package --file pom.xml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 

      # Use an SSH key to connect to the EC2 instance
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}

      # Replace <instance-ip> with your EC2 instance's public IP address or Dns
      - name: Deploy Java Code
        needs: build
        run: |
          sudo ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/id_rsa ubuntu@13.127.46.252 'mkdir -p /usr/share/nginx/html'
          sudo scp -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/id_rsa target/*.war ubuntu@13.127.46.252:/usr/share/nginx/html

         
