name: Deploy Maven Application to AWS Server

on:
  workflow_dispatch

jobs:
  build:
    name: Build Maven Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Or the Java version you're using

      - name: Build with Maven
        run: mvn clean install

  deploy:
    name: Deploy Application to AWS Server
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Copy artifacts to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*.war" # Adjust this to your Maven artifact name
          target: "/usr/share/nginx/html/" # Adjust this to the target location on the server

      - name: SSH into server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx # Adjust this to your application service name
